{% set name = "libunicycle-footstep-planner" %}
{% set version = "0.8.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/robotology/unicycle-footstep-planner/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 852031fabeaf7ea85dc4cd37aca86992f9fa1ad9ee20d07bbd3c4d7d40ad4122

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja
  host:
    - eigen
    - idyntree

test:
  commands:
    - test -f $PREFIX/include/UnicyclePlanner.h  # [unix]
    - test -f $PREFIX/lib/libUnicyclePlanner${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_INC%\\UnicyclePlanner.h exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\UnicyclePlanner.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\UnicyclePlanner.dll exit 1  # [win]

about:
  home: https://github.com/robotology/unicycle-footstep-planner
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Unicycle-based FootStep Planner for humanoid robots.

extra:
  recipe-maintainers:
    - traversaro
    - GiulioRomualdi
