{% set name = "libunicycle-footstep-planner" %}
{% set version = "0.6.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/robotology/unicycle-footstep-planner/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 451f9e14a3f9ad2d17b05bb05d708541a5925c377f47b14dfe451aa8d3708d18

build:
  number: 2
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja
  host:
    - eigen
    - idyntree

test:
  commands:
    - test -f $PREFIX/include/UnicyclePlanner.h  # [unix]
    - test -f $PREFIX/lib/libUnicyclePlanner${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_INC%\\UnicyclePlanner.h exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\UnicyclePlanner.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\UnicyclePlanner.dll exit 1  # [win]

about:
  home: https://github.com/robotology/unicycle-footstep-planner
  license: GPL-2.0-only
  license_file: LICENSE.txt
  summary: Unicycle-based FootStep Planner for humanoid robots.

extra:
  recipe-maintainers:
    - traversaro
    - GiulioRomualdi
